/* Bird dataset for Burma Birds Portal */
const allBirds = [
  {
    id: 1,
    name: "Burmese Bushlark",
    scientific_name: "Mirafra microptera",
    family: "Alaudidae",
    region: "Nationwide",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/203495881/1800",
    photo_credit: "Angadachappa / Macaulay Library",
    description: "An endemic species found in the dry central plains of Burma. It is known for its lark-like appearance and melodious song.",
    habitat: "Dry scrubland, grasslands, and agricultural areas.",
    habitat_group: "Grassland",
    conservation_status: "Least Concern",
    endemic: true
  },
  {
    id: 2,
    name: "White-browed Nuthatch",
    scientific_name: "Sitta victoriae",
    family: "Sittidae",
    region: "Chin",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/48774781/1800",
    photo_credit: "James Eaton / Macaulay Library",
    description: "A rare bird found only in the Chin Hills of western Burma, primarily on Mount Victoria.",
    habitat: "Oak and rhododendron forests at high altitudes.",
    habitat_group: "Mountain",
    conservation_status: "Endangered",
    endemic: true
  },
  {
    id: 3,
    name: "Hooded Treepie",
    scientific_name: "Crypsirina cucullata",
    family: "Corvidae",
    region: "Nationwide",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/306786611/1800",
    photo_credit: "Thibaud Aronson / Macaulay Library",
    description: "A striking-looking treepie of the dry zone with a velvety black hood and long tail.",
    habitat: "Open forests, scrub, and cultivated land with scattered trees.",
    habitat_group: "Scrubland",
    conservation_status: "Near Threatened",
    endemic: true
  },
  {
    id: 4,
    name: "Green Peafowl",
    scientific_name: "Pavo muticus",
    family: "Phasianidae",
    region: "Shan",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/305869381/1800",
    photo_credit: "Peter Ericsson / Macaulay Library",
    description: "A large and magnificent peafowl native to Southeast Asia including Burma.",
    habitat: "Forest edges, grasslands, and riverine habitats.",
    habitat_group: "Riverine",
    conservation_status: "Endangered",
    endemic: false
  },
  {
    id: 5,
    name: "Jerdon's Minivet",
    scientific_name: "Pericrocotus albifrons",
    family: "Campephagidae",
    region: "Nationwide",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/203496031/1800",
    photo_credit: "Angadachappa / Macaulay Library",
    description: "A slender endemic bird of the central dry zone with black and white plumage in the male.",
    habitat: "Acacia scrub and dry open country.",
    habitat_group: "Scrubland",
    conservation_status: "Near Threatened",
    endemic: true
  },
  {
    id: 6,
    name: "Grey-headed Parakeet",
    scientific_name: "Psittacula finschii",
    family: "Psittaculidae",
    region: "Kachin",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/48858591/1800",
    photo_credit: "James Eaton / Macaulay Library",
    description: "A medium-sized parakeet with a grey head, green body, and long tail.",
    habitat: "Broadleaf evergreen and mixed deciduous forests.",
    habitat_group: "Forest",
    conservation_status: "Near Threatened",
    endemic: false
  },
  {
    id: 7,
    name: "Great Hornbill",
    scientific_name: "Buceros bicornis",
    family: "Bucerotidae",
    region: "Tanintharyi",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/302812061/1800",
    photo_credit: "Gaurav Budania / Macaulay Library",
    description: "One of the largest hornbills, famous for its massive bill and powerful wingbeats.",
    habitat: "Mature evergreen and moist deciduous forests.",
    habitat_group: "Forest",
    conservation_status: "Vulnerable",
    endemic: false
  },
  {
    id: 8,
    name: "Ayeyarwady Bulbul",
    scientific_name: "Pycnonotus blanfordi",
    family: "Pycnonotidae",
    region: "Ayeyarwady",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/333795311/1800",
    photo_credit: "Aung Naing Lin / Macaulay Library",
    description: "A familiar bulbul of Burma, often found in gardens, scrub, and open woodland.",
    habitat: "Open woodland, cultivation, scrub, and gardens.",
    habitat_group: "Urban",
    conservation_status: "Least Concern",
    endemic: false
  },
  {
    id: 9,
    name: "Rufous-necked Hornbill",
    scientific_name: "Aceros nipalensis",
    family: "Bucerotidae",
    region: "Chin",
    photo_url: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/43778291/1800",
    photo_credit: "M. Smith / Macaulay Library",
    description: "A large forest hornbill of mountain and foothill forests.",
    habitat: "Evergreen forests and hill forests.",
    habitat_group: "Forest",
    conservation_status: "Vulnerable",
    endemic: false
  },
  {
    id: 10,
    name: "Red-whiskered Bulbul",
    scientific_name: "Pycnonotus jocosus",
    family: "Pycnonotidae",
    region: "Nationwide",
    photo_url: "https://images.unsplash.com/photo-1543946207-39bd91e70ca7?auto=format&fit=crop&w=1200&q=80",
    photo_credit: "Unsplash",
    description: "A lively bulbul often seen in gardens, secondary growth, and urban edges.",
    habitat: "Urban, gardens, scrub, and woodland edges.",
    habitat_group: "Urban",
    conservation_status: "Least Concern",
    endemic: false
  },
  {
    id: 11,
    name: "Jungle Crow",
    scientific_name: "Corvus macrorhynchos",
    family: "Corvidae",
    region: "All over Burma and well up in the hills.",
    photo_url: "https://commons.wikimedia.org/w/index.php?curid=173463293",
    photo_credit: "Tisha Mukherjee / Wikimedia Commons",
    description: "Glossy black coat and large coarse beak; warier than the House Crow.",
    habitat: "Open country, taking the place of crows further east.",
    habitat_group: "Rural",
    conservation_status: "-",
    endemic: false
  },
  {
    id: 12,
    name: "Burmese House Crow",
    scientific_name: "Corvus insolens",
    family: "Corvidae",
    region: "All over Burma and the Shan States.",
    photo_url: "-",
    photo_credit: "-",
    description: "Black coat with a dark brownish-grey neck and light-coloured eyes; smaller than the Jungle Crow.",
    habitat: "Haunts of man, towns, and large villages.",
    habitat_group: "Urban",
    conservation_status: "-",
    endemic: true
  },
  {
    id: 13,
    name: "Indian House Crow",
    scientific_name: "Corvus splendens",
    family: "Corvidae",
    region: "Arracan coast.",
    photo_url: "https://commons.wikimedia.org/w/index.php?curid=2878232",
    photo_credit: "J.M.Garg / Wikimedia Commons",
    description: "Similar to the Burmese House Crow but with a light grey neck.",
    habitat: "Haunts of man.",
    habitat_group: "Urban",
    conservation_status: "-",
    endemic: false
  }
];
